services:
  - type: web
    name: agency2
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true 