services:
  - type: web
    name: agency2
    env: node
    plan: free
    region: oregon
    nodeVersion: 20.11.1
    packageManager: npm
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://wzdavxccbzxnxhdtcjlu.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ZGF2eGNjYnp4bnhoZHRjamx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MTExNjQsImV4cCI6MjA1OTk4NzE2NH0.jN8zWrSEP_0SS32scSg_MwDOLjMNcJPKyw2bkUUJBqE
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        value: sahithkumarpasupuleti@gmail.com
      - key: SMTP_PASSWORD
        value: Sahi@123
      - key: RESEND_API_KEY
        value: re_PteJpSck_PwuUX7jgQSqe5Ga7JUmc5zhr
    healthCheckPath: /
    autoDeploy: true 